name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version major | minor | patch'
        required: true
        default: 'minor'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - name: npm version
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          npm version ${{ github.event.inputs.version }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Release Bot
          message: 'Bump version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
